project:
  type: website
  output-dir: docs
website:
  title: "Sarah Howard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: hw1_questions.qmd
        text: hw1_questions

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



